name: Vite React Typescript Template

on:
  pull_request:
    paths:
      - 'Vite React Typescript Template/**'

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies and run eslint
        run: |
          cd "Vite React Typescript Template"
          npm install
          npm run lint